#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/_common.sh"
activate_paper_env
cd "$ROOT_DIR"

LOG_DIR="${LOG_DIR:-results/logs/non_operator_remaining/worker2}"
mkdir -p "$LOG_DIR"

if [[ -z "${WEATHER_V18_INIT_CHECKPOINT_TEMPLATE:-}" ]]; then
  WEATHER_V18_INIT_CHECKPOINT_TEMPLATE='results/time_series_ssml_topk_sweep_v1/weather/baseline_dml/time_series/{dataset}/{model}_independent_mse_seed{seed}/model.pt'
fi
if [[ -z "${WEATHER_V18_PEER_INIT_CHECKPOINT_TEMPLATE:-}" ]]; then
  WEATHER_V18_PEER_INIT_CHECKPOINT_TEMPLATE='results/time_series_ssml_topk_sweep_v1/weather/baseline_dml/time_series/{dataset}/{model}_independent_mse_seed{seed}/model.pt'
fi

CUDA_VISIBLE_DEVICES="${TIME_SERIES_GPU:-0}" \
GPU="${TIME_SERIES_GPU:-0}" \
OUTPUT_ROOT="${WEATHER_V18_OUTPUT_ROOT:-results/time_series_weather_ssml_rescue_v18}" \
SEEDS="${WEATHER_V18_SEEDS:-0 1 2}" \
MODEL_PAIRS="${WEATHER_V18_MODEL_PAIRS:-patchtst:dlinear transformer:dlinear}" \
BATCH_SIZE="${WEATHER_V18_BATCH_SIZE:-96}" \
REGRESSION_IMITATION_LOSS="${WEATHER_V18_REGRESSION_IMITATION_LOSS:-huber}" \
WARMUP_EPOCHS="${WEATHER_V18_WARMUP_EPOCHS:-1}" \
IMITATION_DECAY_START_EPOCH="${WEATHER_V18_DECAY_START_EPOCH:-2}" \
IMITATION_DECAY_END_EPOCH="${WEATHER_V18_DECAY_END_EPOCH:-20}" \
IMITATION_DECAY_MIN_SCALE="${WEATHER_V18_DECAY_MIN_SCALE:-0.25}" \
SSML_GUIDANCE_MODE="${WEATHER_V18_SSML_GUIDANCE_MODE:-hybrid}" \
SSML_GATE_SCORE_MODE="${WEATHER_V18_SSML_GATE_SCORE_MODE:-peer_better_student_error_relgain}" \
SSML_SCORE_TRANSFORM="${WEATHER_V18_SSML_SCORE_TRANSFORM:-log1p}" \
SSML_TOPK_SCOPE="${WEATHER_V18_SSML_TOPK_SCOPE:-positive}" \
SSML_SUPERVISED_WEIGHT_MODE="${WEATHER_V18_SSML_SUPERVISED_WEIGHT_MODE:-binary}" \
SSML_STUDENT_ONLY="${WEATHER_V18_SSML_STUDENT_ONLY:-1}" \
SSML_FREEZE_PEER="${WEATHER_V18_SSML_FREEZE_PEER:-1}" \
SSML_WORSE_ONLY_UPDATE="${WEATHER_V18_SSML_WORSE_ONLY_UPDATE:-1}" \
SSML_IMITATION_SPACE="${WEATHER_V18_SSML_IMITATION_SPACE:-delta}" \
SSML_ADAPTIVE_DENSE_THRESHOLD="${WEATHER_V18_SSML_ADAPTIVE_DENSE_THRESHOLD:-0.20}" \
SSML_ADAPTIVE_DENSE_TOPK_RATIO="${WEATHER_V18_SSML_ADAPTIVE_DENSE_TOPK_RATIO:-0.60}" \
SSML_ADAPTIVE_DENSE_TOPK_SCOPE="${WEATHER_V18_SSML_ADAPTIVE_DENSE_TOPK_SCOPE:-positive}" \
SSML_ADAPTIVE_DENSE_MAX_SELECTED_RATIO="${WEATHER_V18_SSML_ADAPTIVE_DENSE_MAX_SELECTED_RATIO:-0.25}" \
SSML_ADAPTIVE_DENSE_SCORE_SMOOTHING_KERNEL="${WEATHER_V18_SSML_ADAPTIVE_DENSE_SCORE_SMOOTHING_KERNEL:-11}" \
SSML_ADAPTIVE_DENSE_WINDOW_EXPAND_KERNEL="${WEATHER_V18_SSML_ADAPTIVE_DENSE_WINDOW_EXPAND_KERNEL:-9}" \
INIT_CHECKPOINT_TEMPLATE="${WEATHER_V18_INIT_CHECKPOINT_TEMPLATE}" \
PEER_INIT_CHECKPOINT_TEMPLATE="${WEATHER_V18_PEER_INIT_CHECKPOINT_TEMPLATE}" \
CASE_SPECS="${WEATHER_V18_CASE_SPECS:-delta_cap10:0.06:0.003:0.00:0.10:0.10:3:3:0.20:0.0005 delta_cap15:0.05:0.003:0.00:0.12:0.15:3:5:0.20:0.0005 delta_cap20:0.04:0.002:0.00:0.15:0.20:5:5:0.15:0.0001}" \
LOG_DIR="results/logs/time_series_weather_ssml_v18_worker2" \
run_logged_job \
  "worker2/weather_ssml_v18" \
  "$LOG_DIR/weather_ssml_v18_gpu${TIME_SERIES_GPU:-0}.log" \
  bash scripts/paper_rerun/run_time_series_weather_ssml_v18.sh

echo "[worker2_weather_ssml_v18] job finished"
