#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/_common.sh"
activate_paper_env
cd "$ROOT_DIR"

LOG_DIR="${LOG_DIR:-results/logs/non_operator_remaining/worker3}"
mkdir -p "$LOG_DIR"

CUDA_VISIBLE_DEVICES="${CLASSIFICATION_GPU:-0}" \
GPU="${CLASSIFICATION_GPU:-0}" \
DATASETS="cifar100" \
MODEL_PAIRS="${CLASSIFICATION_BACKUP_MODEL_PAIRS:-resnet18:resnet18}" \
OUTPUT_ROOT="${CLASSIFICATION_BACKUP_OUTPUT_ROOT:-results/classification_ssml_reweight_cifar100_v9_backup}" \
CIFAR10_TOPKS="" \
CIFAR100_TOPKS="${CLASSIFICATION_BACKUP_CIFAR100_TOPKS:-0.35 0.4}" \
SSML_TOPK_SCOPE="${CLASSIFICATION_BACKUP_SSML_TOPK_SCOPE:-positive}" \
SSML_SUPERVISED_HOTSPOT_ALPHA="${CLASSIFICATION_BACKUP_HOTSPOT_ALPHA:-0.15}" \
SSML_SUPERVISED_WEIGHT_MODE="${CLASSIFICATION_BACKUP_WEIGHT_MODE:-binary}" \
SSML_GATE_SCORE_MODE="${CLASSIFICATION_BACKUP_SSML_GATE_SCORE_MODE:-peer_better_true_prob_gap_weighted}" \
SSML_SCORE_TRANSFORM="${CLASSIFICATION_BACKUP_SSML_SCORE_TRANSFORM:-none}" \
SSML_GUIDANCE_MODE="${CLASSIFICATION_BACKUP_SSML_GUIDANCE_MODE:-reweight_only}" \
SSML_PEER_CORRECT_ONLY="${CLASSIFICATION_BACKUP_SSML_PEER_CORRECT_ONLY:-1}" \
SSML_STUDENT_INCORRECT_ONLY="${CLASSIFICATION_BACKUP_SSML_STUDENT_INCORRECT_ONLY:-1}" \
SSML_PEER_TRUE_PROB_THRESHOLD="${CLASSIFICATION_BACKUP_SSML_PEER_TRUE_PROB_THRESHOLD:-0.4}" \
MARGIN="${CLASSIFICATION_BACKUP_MARGIN:-0.03}" \
WARMUP_EPOCHS="${CLASSIFICATION_BACKUP_WARMUP_EPOCHS:-5}" \
IMITATION_DECAY_START_EPOCH="${CLASSIFICATION_BACKUP_DECAY_START_EPOCH:-35}" \
IMITATION_DECAY_END_EPOCH="${CLASSIFICATION_BACKUP_DECAY_END_EPOCH:-85}" \
IMITATION_DECAY_MIN_SCALE="${CLASSIFICATION_BACKUP_DECAY_MIN_SCALE:-0.2}" \
run_logged_job \
  "worker3/classification_reweight_v9_cifar100_backup_gpu${CLASSIFICATION_GPU:-0}" \
  "$LOG_DIR/classification_reweight_v9_cifar100_backup_gpu${CLASSIFICATION_GPU:-0}.log" \
  bash scripts/paper_rerun/run_classification_ssml_reweight_v9.sh

echo "[worker3_classification_ssml_reweight_v9_backup] job finished"
