#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/_common.sh"
activate_paper_env
cd "$ROOT_DIR"

LOG_DIR="${LOG_DIR:-results/logs/non_operator_remaining/worker2}"
mkdir -p "$LOG_DIR"

CUDA_VISIBLE_DEVICES="${TIME_SERIES_GPU:-0}" \
GPU="${TIME_SERIES_GPU:-0}" \
OUTPUT_DIR="${ETTH1_EARLY_STOP_OUTPUT_DIR:-results/time_series_etth1_early_stop_v1}" \
SEEDS="${ETTH1_EARLY_STOP_SEEDS:-0 1 2}" \
MODEL_PAIRS="${ETTH1_EARLY_STOP_MODEL_PAIRS:-transformer:dlinear}" \
INDEPENDENT_MODELS="${ETTH1_EARLY_STOP_INDEPENDENT_MODELS:-transformer}" \
REGRESSION_IMITATION_LOSS="${ETTH1_EARLY_STOP_REGRESSION_IMITATION_LOSS:-huber}" \
LAMBDA_IMITATION="${ETTH1_EARLY_STOP_LAMBDA_IMITATION:-0.001}" \
MARGIN="${ETTH1_EARLY_STOP_MARGIN:-0.02}" \
SSML_TOPK_RATIO="${ETTH1_EARLY_STOP_TOPK_RATIO:-0.02}" \
SSML_SUPERVISED_HOTSPOT_ALPHA="${ETTH1_EARLY_STOP_HOTSPOT_ALPHA:-0.5}" \
SSML_GATE_SCORE_MODE="${ETTH1_EARLY_STOP_SSML_GATE_SCORE_MODE:-peer_better_student_error}" \
SSML_SCORE_TRANSFORM="${ETTH1_EARLY_STOP_SSML_SCORE_TRANSFORM:-none}" \
SSML_GUIDANCE_MODE="${ETTH1_EARLY_STOP_SSML_GUIDANCE_MODE:-reweight_only}" \
HETERO_SSML_ONE_WAY="${ETTH1_EARLY_STOP_ONE_WAY:-1}" \
EPOCHS="${ETTH1_EARLY_STOP_EPOCHS:-15}" \
WARMUP_EPOCHS="${ETTH1_EARLY_STOP_WARMUP_EPOCHS:-5}" \
IMITATION_DECAY_START_EPOCH="${ETTH1_EARLY_STOP_DECAY_START_EPOCH:-10}" \
IMITATION_DECAY_END_EPOCH="${ETTH1_EARLY_STOP_DECAY_END_EPOCH:-50}" \
IMITATION_DECAY_MIN_SCALE="${ETTH1_EARLY_STOP_DECAY_MIN_SCALE:-0.1}" \
EARLY_STOP_PATIENCE="${ETTH1_EARLY_STOP_PATIENCE:-2}" \
EARLY_STOP_MIN_EPOCHS="${ETTH1_EARLY_STOP_MIN_EPOCHS:-4}" \
EARLY_STOP_MIN_DELTA="${ETTH1_EARLY_STOP_MIN_DELTA:-0.0005}" \
LIVE_PLOT_INTERVAL="${ETTH1_EARLY_STOP_LIVE_PLOT_INTERVAL:-1}" \
run_logged_job \
  "worker2/etth1_early_stop_v1" \
  "$LOG_DIR/etth1_early_stop_v1_gpu${TIME_SERIES_GPU:-0}.log" \
  bash scripts/paper_rerun/run_time_series_etth1_early_stop_v1.sh

echo "[worker2_etth1_early_stop_v1] job finished"
