#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/_common.sh"
activate_paper_env
cd "$ROOT_DIR"

LOG_DIR="${LOG_DIR:-results/logs/non_operator_remaining/worker1}"
mkdir -p "$LOG_DIR"

run_cifar10() {
  CUDA_VISIBLE_DEVICES="${CLASSIFICATION_GPU0:-0}" \
  GPU="${CLASSIFICATION_GPU0:-0}" \
  DATASETS="cifar10" \
  OUTPUT_ROOT="${CLASSIFICATION_CIFAR10_OUTPUT_ROOT:-results/classification_ssml_reweight_cifar10_v7}" \
  CIFAR10_TOPKS="${CLASSIFICATION_CIFAR10_TOPKS:-0.2 0.3}" \
  CIFAR100_TOPKS="" \
  SSML_TOPK_SCOPE="${CLASSIFICATION_CIFAR10_SSML_TOPK_SCOPE:-positive}" \
  SSML_SUPERVISED_HOTSPOT_ALPHA="${CLASSIFICATION_CIFAR10_HOTSPOT_ALPHA:-0.5}" \
  SSML_GATE_SCORE_MODE="${CLASSIFICATION_CIFAR10_SSML_GATE_SCORE_MODE:-peer_better_student_error}" \
  SSML_SCORE_TRANSFORM="${CLASSIFICATION_CIFAR10_SSML_SCORE_TRANSFORM:-log1p}" \
  SSML_GUIDANCE_MODE="${CLASSIFICATION_CIFAR10_SSML_GUIDANCE_MODE:-reweight_only}" \
  SSML_PEER_CORRECT_ONLY="${CLASSIFICATION_CIFAR10_SSML_PEER_CORRECT_ONLY:-1}" \
  SSML_STUDENT_INCORRECT_ONLY="${CLASSIFICATION_CIFAR10_SSML_STUDENT_INCORRECT_ONLY:-1}" \
  SSML_PEER_TRUE_PROB_THRESHOLD="${CLASSIFICATION_CIFAR10_SSML_PEER_TRUE_PROB_THRESHOLD:-0.3}" \
  WARMUP_EPOCHS="${CLASSIFICATION_CIFAR10_WARMUP_EPOCHS:-5}" \
  IMITATION_DECAY_START_EPOCH="${CLASSIFICATION_CIFAR10_DECAY_START_EPOCH:-35}" \
  IMITATION_DECAY_END_EPOCH="${CLASSIFICATION_CIFAR10_DECAY_END_EPOCH:-85}" \
  IMITATION_DECAY_MIN_SCALE="${CLASSIFICATION_CIFAR10_DECAY_MIN_SCALE:-0.2}" \
  run_logged_job \
    "worker1/classification_reweight_v7_cifar10_gpu${CLASSIFICATION_GPU0:-0}" \
    "$LOG_DIR/classification_reweight_v7_cifar10_gpu${CLASSIFICATION_GPU0:-0}.log" \
    bash scripts/paper_rerun/run_classification_ssml_reweight_v7.sh
}

run_cifar100() {
  CUDA_VISIBLE_DEVICES="${CLASSIFICATION_GPU1:-1}" \
  GPU="${CLASSIFICATION_GPU1:-1}" \
  DATASETS="cifar100" \
  OUTPUT_ROOT="${CLASSIFICATION_CIFAR100_OUTPUT_ROOT:-results/classification_ssml_reweight_cifar100_v7}" \
  CIFAR10_TOPKS="" \
  CIFAR100_TOPKS="${CLASSIFICATION_CIFAR100_TOPKS:-0.2 0.35}" \
  SSML_TOPK_SCOPE="${CLASSIFICATION_CIFAR100_SSML_TOPK_SCOPE:-positive}" \
  SSML_SUPERVISED_HOTSPOT_ALPHA="${CLASSIFICATION_CIFAR100_HOTSPOT_ALPHA:-0.25}" \
  SSML_GATE_SCORE_MODE="${CLASSIFICATION_CIFAR100_SSML_GATE_SCORE_MODE:-peer_better_student_error}" \
  SSML_SCORE_TRANSFORM="${CLASSIFICATION_CIFAR100_SSML_SCORE_TRANSFORM:-log1p}" \
  SSML_GUIDANCE_MODE="${CLASSIFICATION_CIFAR100_SSML_GUIDANCE_MODE:-reweight_only}" \
  SSML_PEER_CORRECT_ONLY="${CLASSIFICATION_CIFAR100_SSML_PEER_CORRECT_ONLY:-1}" \
  SSML_STUDENT_INCORRECT_ONLY="${CLASSIFICATION_CIFAR100_SSML_STUDENT_INCORRECT_ONLY:-1}" \
  SSML_PEER_TRUE_PROB_THRESHOLD="${CLASSIFICATION_CIFAR100_SSML_PEER_TRUE_PROB_THRESHOLD:-0.5}" \
  WARMUP_EPOCHS="${CLASSIFICATION_CIFAR100_WARMUP_EPOCHS:-10}" \
  IMITATION_DECAY_START_EPOCH="${CLASSIFICATION_CIFAR100_DECAY_START_EPOCH:-45}" \
  IMITATION_DECAY_END_EPOCH="${CLASSIFICATION_CIFAR100_DECAY_END_EPOCH:-95}" \
  IMITATION_DECAY_MIN_SCALE="${CLASSIFICATION_CIFAR100_DECAY_MIN_SCALE:-0.2}" \
  run_logged_job \
    "worker1/classification_reweight_v7_cifar100_gpu${CLASSIFICATION_GPU1:-1}" \
    "$LOG_DIR/classification_reweight_v7_cifar100_gpu${CLASSIFICATION_GPU1:-1}.log" \
    bash scripts/paper_rerun/run_classification_ssml_reweight_v7.sh
}

run_cifar10 &
PID0=$!
run_cifar100 &
PID1=$!

echo "[worker1_classification_ssml_reweight_v7] started cifar10 pid=$PID0 gpu=${CLASSIFICATION_GPU0:-0}"
echo "[worker1_classification_ssml_reweight_v7] started cifar100 pid=$PID1 gpu=${CLASSIFICATION_GPU1:-1}"

wait "$PID0"
wait "$PID1"
echo "[worker1_classification_ssml_reweight_v7] all jobs finished"
