#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/_common.sh"
activate_paper_env
cd "$ROOT_DIR"

LOG_DIR="${LOG_DIR:-results/logs/non_operator_remaining/worker2}"
mkdir -p "$LOG_DIR"

if [[ -z "${WEATHER_V19_INIT_CHECKPOINT_TEMPLATE:-}" ]]; then
  WEATHER_V19_INIT_CHECKPOINT_TEMPLATE='results/time_series_ssml_topk_sweep_v1/weather/baseline_dml/time_series/{dataset}/{model}_independent_mse_seed{seed}/model.pt'
fi
if [[ -z "${WEATHER_V19_PEER_INIT_CHECKPOINT_TEMPLATE:-}" ]]; then
  WEATHER_V19_PEER_INIT_CHECKPOINT_TEMPLATE='results/time_series_ssml_topk_sweep_v1/weather/baseline_dml/time_series/{dataset}/{model}_independent_mse_seed{seed}/model.pt'
fi

CUDA_VISIBLE_DEVICES="${TIME_SERIES_GPU:-0}" \
GPU="${TIME_SERIES_GPU:-0}" \
OUTPUT_ROOT="${WEATHER_V19_OUTPUT_ROOT:-results/time_series_weather_ssml_rescue_v19}" \
SEEDS="${WEATHER_V19_SEEDS:-0 1 2}" \
MODEL_PAIRS="${WEATHER_V19_MODEL_PAIRS:-transformer:dlinear}" \
BATCH_SIZE="${WEATHER_V19_BATCH_SIZE:-96}" \
REGRESSION_IMITATION_LOSS="${WEATHER_V19_REGRESSION_IMITATION_LOSS:-huber}" \
WARMUP_EPOCHS="${WEATHER_V19_WARMUP_EPOCHS:-1}" \
IMITATION_DECAY_START_EPOCH="${WEATHER_V19_DECAY_START_EPOCH:-2}" \
IMITATION_DECAY_END_EPOCH="${WEATHER_V19_DECAY_END_EPOCH:-20}" \
IMITATION_DECAY_MIN_SCALE="${WEATHER_V19_DECAY_MIN_SCALE:-0.25}" \
SSML_GUIDANCE_MODE="${WEATHER_V19_SSML_GUIDANCE_MODE:-hybrid}" \
SSML_GATE_SCORE_MODE="${WEATHER_V19_SSML_GATE_SCORE_MODE:-peer_better_student_error_relgain}" \
SSML_SCORE_TRANSFORM="${WEATHER_V19_SSML_SCORE_TRANSFORM:-log1p}" \
SSML_TOPK_SCOPE="${WEATHER_V19_SSML_TOPK_SCOPE:-positive}" \
SSML_SUPERVISED_WEIGHT_MODE="${WEATHER_V19_SSML_SUPERVISED_WEIGHT_MODE:-binary}" \
SSML_STUDENT_ONLY="${WEATHER_V19_SSML_STUDENT_ONLY:-1}" \
SSML_FREEZE_PEER="${WEATHER_V19_SSML_FREEZE_PEER:-1}" \
SSML_WORSE_ONLY_UPDATE="${WEATHER_V19_SSML_WORSE_ONLY_UPDATE:-1}" \
SSML_IMITATION_SPACE="${WEATHER_V19_SSML_IMITATION_SPACE:-residual}" \
SSML_RESIDUAL_SPACE_KERNEL="${WEATHER_V19_SSML_RESIDUAL_SPACE_KERNEL:-11}" \
SSML_CONFLICT_AWARE_PROJECTION="${WEATHER_V19_SSML_CONFLICT_AWARE_PROJECTION:-1}" \
SSML_ADAPTIVE_DENSE_THRESHOLD="${WEATHER_V19_SSML_ADAPTIVE_DENSE_THRESHOLD:-0.20}" \
SSML_ADAPTIVE_DENSE_TOPK_RATIO="${WEATHER_V19_SSML_ADAPTIVE_DENSE_TOPK_RATIO:-0.80}" \
SSML_ADAPTIVE_DENSE_TOPK_SCOPE="${WEATHER_V19_SSML_ADAPTIVE_DENSE_TOPK_SCOPE:-positive}" \
SSML_ADAPTIVE_DENSE_MAX_SELECTED_RATIO="${WEATHER_V19_SSML_ADAPTIVE_DENSE_MAX_SELECTED_RATIO:-0.30}" \
SSML_ADAPTIVE_DENSE_SCORE_SMOOTHING_KERNEL="${WEATHER_V19_SSML_ADAPTIVE_DENSE_SCORE_SMOOTHING_KERNEL:-11}" \
SSML_ADAPTIVE_DENSE_WINDOW_EXPAND_KERNEL="${WEATHER_V19_SSML_ADAPTIVE_DENSE_WINDOW_EXPAND_KERNEL:-9}" \
SSML_WINDOW_SCORE_KERNEL="${WEATHER_V19_SSML_WINDOW_SCORE_KERNEL:-9}" \
INIT_CHECKPOINT_TEMPLATE="${WEATHER_V19_INIT_CHECKPOINT_TEMPLATE}" \
PEER_INIT_CHECKPOINT_TEMPLATE="${WEATHER_V19_PEER_INIT_CHECKPOINT_TEMPLATE}" \
CASE_SPECS="${WEATHER_V19_CASE_SPECS:-reswin_t30:0.08:0.0020:0.00:0.30:0.20:3:7:0.30:0.0010 reswin_t50:0.06:0.0015:0.00:0.50:0.25:5:9:0.25:0.0010 reswin_t100:0.05:0.0010:0.00:1.00:0.30:7:11:0.20:0.0005}" \
LOG_DIR="results/logs/time_series_weather_ssml_v19_worker2" \
run_logged_job \
  "worker2/weather_ssml_v19" \
  "$LOG_DIR/weather_ssml_v19_gpu${TIME_SERIES_GPU:-0}.log" \
  bash scripts/paper_rerun/run_time_series_weather_ssml_v19.sh

echo "[worker2_weather_ssml_v19] job finished"
