#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_common.sh"
activate_paper_env
cd "$ROOT_DIR"

LOG_DIR="${LOG_DIR:-results/logs/time_series_ssml_topk_sweep}"
mkdir -p "$LOG_DIR"

DEVICE="${DEVICE:-cuda}"
GPU="${GPU:-0}"
SEEDS="${SEEDS:-0 1 2}"
MODEL_PAIRS="${MODEL_PAIRS:-transformer:dlinear dlinear:transformer}"
NUM_WORKERS="${NUM_WORKERS:-4}"
BATCH_SIZE="${BATCH_SIZE:-64}"
SEQ_LEN="${SEQ_LEN:-96}"
PRED_LENS="${PRED_LENS:-24}"
FEATURE_MODE="${FEATURE_MODE:-multivariate}"
OUTPUT_ROOT="${OUTPUT_ROOT:-results/time_series_ssml_topk_sweep_v1}"
INCLUDE_BASELINES="${INCLUDE_BASELINES:-1}"

WEATHER_TOPKS="${WEATHER_TOPKS:-0.005 0.01 0.02 0.05}"
WEATHER_EPOCHS="${WEATHER_EPOCHS:-60}"
WEATHER_REGRESSION_IMITATION_LOSS="${WEATHER_REGRESSION_IMITATION_LOSS:-mse}"
WEATHER_LAMBDA_IMITATION="${WEATHER_LAMBDA_IMITATION:-0.1}"
WEATHER_MARGIN="${WEATHER_MARGIN:-0.05}"
WEATHER_WARMUP_EPOCHS="${WEATHER_WARMUP_EPOCHS:-5}"
WEATHER_DECAY_START_EPOCH="${WEATHER_DECAY_START_EPOCH:-20}"
WEATHER_DECAY_END_EPOCH="${WEATHER_DECAY_END_EPOCH:-50}"
WEATHER_DECAY_MIN_SCALE="${WEATHER_DECAY_MIN_SCALE:-0.05}"
WEATHER_HETERO_SSML_ONE_WAY="${WEATHER_HETERO_SSML_ONE_WAY:-1}"

ETTH1_TOPKS="${ETTH1_TOPKS:-0.005 0.01 0.02 0.05}"
ETTH1_EPOCHS="${ETTH1_EPOCHS:-60}"
ETTH1_REGRESSION_IMITATION_LOSS="${ETTH1_REGRESSION_IMITATION_LOSS:-huber}"
ETTH1_LAMBDA_IMITATION="${ETTH1_LAMBDA_IMITATION:-0.01}"
ETTH1_MARGIN="${ETTH1_MARGIN:-0.05}"
ETTH1_WARMUP_EPOCHS="${ETTH1_WARMUP_EPOCHS:-20}"
ETTH1_DECAY_START_EPOCH="${ETTH1_DECAY_START_EPOCH:-25}"
ETTH1_DECAY_END_EPOCH="${ETTH1_DECAY_END_EPOCH:-35}"
ETTH1_DECAY_MIN_SCALE="${ETTH1_DECAY_MIN_SCALE:-0.0}"
ETTH1_HETERO_SSML_ONE_WAY="${ETTH1_HETERO_SSML_ONE_WAY:-0}"

slug_float() {
  local value="${1//./p}"
  value="${value//-/m}"
  printf '%s\n' "$value"
}

run_core_job() {
  local label="$1"
  shift
  run_logged_job \
    "time_series_topk/$label" \
    "$LOG_DIR/$label.log" \
    env \
      CUDA_VISIBLE_DEVICES="$GPU" \
      DEVICE="$DEVICE" \
      MODEL_PAIRS="$MODEL_PAIRS" \
      REQUIRE_DISTINCT_PEER="1" \
      SEEDS="$SEEDS" \
      BATCH_SIZE="$BATCH_SIZE" \
      NUM_WORKERS="$NUM_WORKERS" \
      SEQ_LEN="$SEQ_LEN" \
      PRED_LENS="$PRED_LENS" \
      FEATURE_MODE="$FEATURE_MODE" \
      "$@" \
      bash scripts/paper_rerun/run_core_time_series.sh
}

echo "[time_series_ssml_topk_sweep] output_root=$OUTPUT_ROOT"
echo "[time_series_ssml_topk_sweep] gpu=$GPU"
echo "[time_series_ssml_topk_sweep] weather_topks=$WEATHER_TOPKS"
echo "[time_series_ssml_topk_sweep] etth1_topks=$ETTH1_TOPKS"

if [[ "$INCLUDE_BASELINES" == "1" ]]; then
  run_core_job \
    "weather_baseline_dml" \
    DATASETS="weather" \
    METHODS="independent dml" \
    EPOCHS="$WEATHER_EPOCHS" \
    REGRESSION_IMITATION_LOSS="$WEATHER_REGRESSION_IMITATION_LOSS" \
    LAMBDA_IMITATION="$WEATHER_LAMBDA_IMITATION" \
    MARGIN="$WEATHER_MARGIN" \
    WARMUP_EPOCHS="$WEATHER_WARMUP_EPOCHS" \
    IMITATION_DECAY_START_EPOCH="$WEATHER_DECAY_START_EPOCH" \
    IMITATION_DECAY_END_EPOCH="$WEATHER_DECAY_END_EPOCH" \
    IMITATION_DECAY_MIN_SCALE="$WEATHER_DECAY_MIN_SCALE" \
    HETERO_SSML_ONE_WAY="$WEATHER_HETERO_SSML_ONE_WAY" \
    SSML_TOPK_RATIO="0.0" \
    OUTPUT_DIR="$OUTPUT_ROOT/weather/baseline_dml"

  run_core_job \
    "etth1_baseline_dml" \
    DATASETS="etth1" \
    METHODS="independent dml" \
    EPOCHS="$ETTH1_EPOCHS" \
    REGRESSION_IMITATION_LOSS="$ETTH1_REGRESSION_IMITATION_LOSS" \
    LAMBDA_IMITATION="$ETTH1_LAMBDA_IMITATION" \
    MARGIN="$ETTH1_MARGIN" \
    WARMUP_EPOCHS="$ETTH1_WARMUP_EPOCHS" \
    IMITATION_DECAY_START_EPOCH="$ETTH1_DECAY_START_EPOCH" \
    IMITATION_DECAY_END_EPOCH="$ETTH1_DECAY_END_EPOCH" \
    IMITATION_DECAY_MIN_SCALE="$ETTH1_DECAY_MIN_SCALE" \
    HETERO_SSML_ONE_WAY="$ETTH1_HETERO_SSML_ONE_WAY" \
    SSML_TOPK_RATIO="0.0" \
    OUTPUT_DIR="$OUTPUT_ROOT/etth1/baseline_dml"
fi

for topk in $WEATHER_TOPKS; do
  topk_slug="$(slug_float "$topk")"
  run_core_job \
    "weather_ssml_t${topk_slug}" \
    DATASETS="weather" \
    METHODS="ssml" \
    EPOCHS="$WEATHER_EPOCHS" \
    REGRESSION_IMITATION_LOSS="$WEATHER_REGRESSION_IMITATION_LOSS" \
    LAMBDA_IMITATION="$WEATHER_LAMBDA_IMITATION" \
    MARGIN="$WEATHER_MARGIN" \
    WARMUP_EPOCHS="$WEATHER_WARMUP_EPOCHS" \
    IMITATION_DECAY_START_EPOCH="$WEATHER_DECAY_START_EPOCH" \
    IMITATION_DECAY_END_EPOCH="$WEATHER_DECAY_END_EPOCH" \
    IMITATION_DECAY_MIN_SCALE="$WEATHER_DECAY_MIN_SCALE" \
    HETERO_SSML_ONE_WAY="$WEATHER_HETERO_SSML_ONE_WAY" \
    SSML_TOPK_RATIO="$topk" \
    OUTPUT_DIR="$OUTPUT_ROOT/weather/ssml_t${topk_slug}"
done

for topk in $ETTH1_TOPKS; do
  topk_slug="$(slug_float "$topk")"
  run_core_job \
    "etth1_ssml_t${topk_slug}" \
    DATASETS="etth1" \
    METHODS="ssml" \
    EPOCHS="$ETTH1_EPOCHS" \
    REGRESSION_IMITATION_LOSS="$ETTH1_REGRESSION_IMITATION_LOSS" \
    LAMBDA_IMITATION="$ETTH1_LAMBDA_IMITATION" \
    MARGIN="$ETTH1_MARGIN" \
    WARMUP_EPOCHS="$ETTH1_WARMUP_EPOCHS" \
    IMITATION_DECAY_START_EPOCH="$ETTH1_DECAY_START_EPOCH" \
    IMITATION_DECAY_END_EPOCH="$ETTH1_DECAY_END_EPOCH" \
    IMITATION_DECAY_MIN_SCALE="$ETTH1_DECAY_MIN_SCALE" \
    HETERO_SSML_ONE_WAY="$ETTH1_HETERO_SSML_ONE_WAY" \
    SSML_TOPK_RATIO="$topk" \
    OUTPUT_DIR="$OUTPUT_ROOT/etth1/ssml_t${topk_slug}"
done
