#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_common.sh"
activate_paper_env
cd "$ROOT_DIR"

SEEDS="${SEEDS:-0 1 2}"
EPOCHS="${EPOCHS:-60}"
BATCH_SIZE="${BATCH_SIZE:-64}"
NUM_WORKERS="${NUM_WORKERS:-4}"
DEVICE="${DEVICE:-cuda}"
OUTPUT_DIR="${OUTPUT_DIR:-results/time_series_weather_confirm_v1}"
MODEL_PAIRS="${MODEL_PAIRS:-transformer:dlinear dlinear:transformer}"
REGRESSION_IMITATION_LOSS="${REGRESSION_IMITATION_LOSS:-mse}"
LAMBDA_IMITATION="${LAMBDA_IMITATION:-0.1}"
MARGIN="${MARGIN:-0.05}"
WARMUP_EPOCHS="${WARMUP_EPOCHS:-5}"
IMITATION_DECAY_START_EPOCH="${IMITATION_DECAY_START_EPOCH:-20}"
IMITATION_DECAY_END_EPOCH="${IMITATION_DECAY_END_EPOCH:-50}"
IMITATION_DECAY_MIN_SCALE="${IMITATION_DECAY_MIN_SCALE:-0.05}"
HETERO_SSML_ONE_WAY="${HETERO_SSML_ONE_WAY:-1}"
SSML_TOPK_RATIO="${SSML_TOPK_RATIO:-0.1}"

echo "[time_series_weather_confirm] output_dir=$OUTPUT_DIR"
echo "[time_series_weather_confirm] methods=independent dml ssml"
echo "[time_series_weather_confirm] model_pairs=$MODEL_PAIRS"
echo "[time_series_weather_confirm] lambda=$LAMBDA_IMITATION margin=$MARGIN topk=$SSML_TOPK_RATIO warmup=$WARMUP_EPOCHS"

METHODS="independent dml ssml" \
DATASETS="weather" \
MODEL_PAIRS="$MODEL_PAIRS" \
SEEDS="$SEEDS" \
EPOCHS="$EPOCHS" \
BATCH_SIZE="$BATCH_SIZE" \
NUM_WORKERS="$NUM_WORKERS" \
DEVICE="$DEVICE" \
OUTPUT_DIR="$OUTPUT_DIR" \
REGRESSION_IMITATION_LOSS="$REGRESSION_IMITATION_LOSS" \
LAMBDA_IMITATION="$LAMBDA_IMITATION" \
MARGIN="$MARGIN" \
WARMUP_EPOCHS="$WARMUP_EPOCHS" \
IMITATION_DECAY_START_EPOCH="$IMITATION_DECAY_START_EPOCH" \
IMITATION_DECAY_END_EPOCH="$IMITATION_DECAY_END_EPOCH" \
IMITATION_DECAY_MIN_SCALE="$IMITATION_DECAY_MIN_SCALE" \
HETERO_SSML_ONE_WAY="$HETERO_SSML_ONE_WAY" \
SSML_TOPK_RATIO="$SSML_TOPK_RATIO" \
bash scripts/paper_rerun/run_core_time_series.sh
