#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_common.sh"
activate_paper_env
cd "$ROOT_DIR"

SEEDS="${SEEDS:-0 1 2}"
EPOCHS="${EPOCHS:-60}"
BATCH_SIZE="${BATCH_SIZE:-64}"
NUM_WORKERS="${NUM_WORKERS:-4}"
DEVICE="${DEVICE:-cuda}"
OUTPUT_DIR="${OUTPUT_DIR:-results/time_series_ssml_tuned_v1}"
SEQ_LEN="${SEQ_LEN:-96}"
PRED_LENS="${PRED_LENS:-24}"
REGRESSION_IMITATION_LOSS="${REGRESSION_IMITATION_LOSS:-mse}"
LAMBDA_IMITATION="${LAMBDA_IMITATION:-0.3}"
MARGIN="${MARGIN:-0.05}"
WARMUP_EPOCHS="${WARMUP_EPOCHS:-5}"
IMITATION_DECAY_START_EPOCH="${IMITATION_DECAY_START_EPOCH:-20}"
IMITATION_DECAY_END_EPOCH="${IMITATION_DECAY_END_EPOCH:-50}"
IMITATION_DECAY_MIN_SCALE="${IMITATION_DECAY_MIN_SCALE:-0.1}"
HETERO_SSML_ONE_WAY="${HETERO_SSML_ONE_WAY:-1}"
SSML_TOPK_RATIO="${SSML_TOPK_RATIO:-0.3}"
FEATURE_MODE="${FEATURE_MODE:-multivariate}"

echo "[time_series_ssml_tuned] output_dir=$OUTPUT_DIR"
echo "[time_series_ssml_tuned] methods=independent dml ssml"
echo "[time_series_ssml_tuned] lambda=$LAMBDA_IMITATION margin=$MARGIN warmup=$WARMUP_EPOCHS topk=$SSML_TOPK_RATIO"
echo "[time_series_ssml_tuned] decay=[$IMITATION_DECAY_START_EPOCH,$IMITATION_DECAY_END_EPOCH] min_scale=$IMITATION_DECAY_MIN_SCALE"
echo "[time_series_ssml_tuned] hetero_ssml_one_way=$HETERO_SSML_ONE_WAY"

METHODS="independent dml ssml" \
DATASETS="etth1 electricity weather" \
MODEL_PAIRS="transformer:dlinear" \
SEEDS="$SEEDS" \
EPOCHS="$EPOCHS" \
BATCH_SIZE="$BATCH_SIZE" \
NUM_WORKERS="$NUM_WORKERS" \
DEVICE="$DEVICE" \
OUTPUT_DIR="$OUTPUT_DIR" \
SEQ_LEN="$SEQ_LEN" \
PRED_LENS="$PRED_LENS" \
REGRESSION_IMITATION_LOSS="$REGRESSION_IMITATION_LOSS" \
LAMBDA_IMITATION="$LAMBDA_IMITATION" \
MARGIN="$MARGIN" \
WARMUP_EPOCHS="$WARMUP_EPOCHS" \
IMITATION_DECAY_START_EPOCH="$IMITATION_DECAY_START_EPOCH" \
IMITATION_DECAY_END_EPOCH="$IMITATION_DECAY_END_EPOCH" \
IMITATION_DECAY_MIN_SCALE="$IMITATION_DECAY_MIN_SCALE" \
HETERO_SSML_ONE_WAY="$HETERO_SSML_ONE_WAY" \
SSML_TOPK_RATIO="$SSML_TOPK_RATIO" \
FEATURE_MODE="$FEATURE_MODE" \
bash scripts/paper_rerun/run_core_time_series.sh
