#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_common.sh"
activate_paper_env
cd "$ROOT_DIR"

METHODS="${METHODS:-independent dml ssml}"
DATASETS="${DATASETS:-darcy}"
SEEDS="${SEEDS:-0 1 2}"
MODEL_PAIRS="${MODEL_PAIRS:-fno:deeponet}"
INDEPENDENT_MODELS="${INDEPENDENT_MODELS:-$(collect_unique_models "$MODEL_PAIRS")}"
REQUIRE_DISTINCT_PEER="${REQUIRE_DISTINCT_PEER:-1}"
EPOCHS="${EPOCHS:-150}"
BATCH_SIZE="${BATCH_SIZE:-16}"
NUM_WORKERS="${NUM_WORKERS:-4}"
DEVICE="${DEVICE:-cuda}"
OUTPUT_DIR="${OUTPUT_DIR:-results/operator_ssml_tuned_v1}"
REGRESSION_IMITATION_LOSS="${REGRESSION_IMITATION_LOSS:-mse}"
LAMBDA_IMITATION="${LAMBDA_IMITATION:-0.3}"
MARGIN="${MARGIN:-0.02}"
WARMUP_EPOCHS="${WARMUP_EPOCHS:-5}"
IMITATION_DECAY_START_EPOCH="${IMITATION_DECAY_START_EPOCH:-30}"
IMITATION_DECAY_END_EPOCH="${IMITATION_DECAY_END_EPOCH:-120}"
IMITATION_DECAY_MIN_SCALE="${IMITATION_DECAY_MIN_SCALE:-0.1}"
HETERO_SSML_ONE_WAY="${HETERO_SSML_ONE_WAY:-1}"
DOWNLOAD="${DOWNLOAD:-0}"

echo "[operator_recommended] output_dir=$OUTPUT_DIR"
echo "[operator_recommended] methods=$METHODS"
echo "[operator_recommended] datasets=$DATASETS"
echo "[operator_recommended] model_pairs=$MODEL_PAIRS"
echo "[operator_recommended] lambda=$LAMBDA_IMITATION margin=$MARGIN warmup=$WARMUP_EPOCHS"
echo "[operator_recommended] decay=[$IMITATION_DECAY_START_EPOCH,$IMITATION_DECAY_END_EPOCH] min_scale=$IMITATION_DECAY_MIN_SCALE"
echo "[operator_recommended] hetero_ssml_one_way=$HETERO_SSML_ONE_WAY"

METHODS="$METHODS" \
DATASETS="$DATASETS" \
SEEDS="$SEEDS" \
MODEL_PAIRS="$MODEL_PAIRS" \
INDEPENDENT_MODELS="$INDEPENDENT_MODELS" \
REQUIRE_DISTINCT_PEER="$REQUIRE_DISTINCT_PEER" \
EPOCHS="$EPOCHS" \
BATCH_SIZE="$BATCH_SIZE" \
NUM_WORKERS="$NUM_WORKERS" \
DEVICE="$DEVICE" \
OUTPUT_DIR="$OUTPUT_DIR" \
REGRESSION_IMITATION_LOSS="$REGRESSION_IMITATION_LOSS" \
LAMBDA_IMITATION="$LAMBDA_IMITATION" \
MARGIN="$MARGIN" \
WARMUP_EPOCHS="$WARMUP_EPOCHS" \
IMITATION_DECAY_START_EPOCH="$IMITATION_DECAY_START_EPOCH" \
IMITATION_DECAY_END_EPOCH="$IMITATION_DECAY_END_EPOCH" \
IMITATION_DECAY_MIN_SCALE="$IMITATION_DECAY_MIN_SCALE" \
HETERO_SSML_ONE_WAY="$HETERO_SSML_ONE_WAY" \
DOWNLOAD="$DOWNLOAD" \
bash scripts/paper_rerun/run_core_operator.sh
