#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_common.sh"
activate_paper_env
cd "$ROOT_DIR"

SEEDS="${SEEDS:-0 1 2}"
EPOCHS="${EPOCHS:-100}"
BATCH_SIZE="${BATCH_SIZE:-128}"
NUM_WORKERS="${NUM_WORKERS:-8}"
DEVICE="${DEVICE:-cuda}"
OUTPUT_DIR="${OUTPUT_DIR:-results/classification_ssml_tuned_v1}"
CLASSIFICATION_IMITATION_LOSS="${CLASSIFICATION_IMITATION_LOSS:-kl}"
DISTILL_TEMPERATURE="${DISTILL_TEMPERATURE:-2.0}"
LAMBDA_IMITATION="${LAMBDA_IMITATION:-0.3}"
MARGIN="${MARGIN:-0.05}"
WARMUP_EPOCHS="${WARMUP_EPOCHS:-5}"
IMITATION_DECAY_START_EPOCH="${IMITATION_DECAY_START_EPOCH:-30}"
IMITATION_DECAY_END_EPOCH="${IMITATION_DECAY_END_EPOCH:-90}"
IMITATION_DECAY_MIN_SCALE="${IMITATION_DECAY_MIN_SCALE:-0.1}"
HETERO_SSML_ONE_WAY="${HETERO_SSML_ONE_WAY:-1}"
DOWNLOAD="${DOWNLOAD:-1}"
LABEL_NOISE_CONDITIONS="${LABEL_NOISE_CONDITIONS:-none:0.0}"

echo "[classification_ssml_tuned] output_dir=$OUTPUT_DIR"
echo "[classification_ssml_tuned] methods=independent dml ssml"
echo "[classification_ssml_tuned] lambda=$LAMBDA_IMITATION margin=$MARGIN warmup=$WARMUP_EPOCHS"
echo "[classification_ssml_tuned] decay=[$IMITATION_DECAY_START_EPOCH,$IMITATION_DECAY_END_EPOCH] min_scale=$IMITATION_DECAY_MIN_SCALE"
echo "[classification_ssml_tuned] hetero_ssml_one_way=$HETERO_SSML_ONE_WAY"

METHODS="independent dml ssml" \
DATASETS="cifar10 cifar100" \
MODEL_PAIRS="resnet18:vit_b16" \
SEEDS="$SEEDS" \
EPOCHS="$EPOCHS" \
BATCH_SIZE="$BATCH_SIZE" \
NUM_WORKERS="$NUM_WORKERS" \
DEVICE="$DEVICE" \
OUTPUT_DIR="$OUTPUT_DIR" \
CLASSIFICATION_IMITATION_LOSS="$CLASSIFICATION_IMITATION_LOSS" \
DISTILL_TEMPERATURE="$DISTILL_TEMPERATURE" \
LAMBDA_IMITATION="$LAMBDA_IMITATION" \
MARGIN="$MARGIN" \
WARMUP_EPOCHS="$WARMUP_EPOCHS" \
IMITATION_DECAY_START_EPOCH="$IMITATION_DECAY_START_EPOCH" \
IMITATION_DECAY_END_EPOCH="$IMITATION_DECAY_END_EPOCH" \
IMITATION_DECAY_MIN_SCALE="$IMITATION_DECAY_MIN_SCALE" \
HETERO_SSML_ONE_WAY="$HETERO_SSML_ONE_WAY" \
DOWNLOAD="$DOWNLOAD" \
LABEL_NOISE_CONDITIONS="$LABEL_NOISE_CONDITIONS" \
bash scripts/paper_rerun/run_core_classification.sh
