#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_common.sh"
activate_paper_env
cd "$ROOT_DIR"

DEVICE="${DEVICE:-cuda}"
GPU="${GPU:-0}"
SEEDS="${SEEDS:-0 1 2}"
MODEL_PAIRS="${MODEL_PAIRS:-transformer:dlinear}"
EPOCHS="${EPOCHS:-60}"
BATCH_SIZE="${BATCH_SIZE:-64}"
NUM_WORKERS="${NUM_WORKERS:-4}"
SEQ_LEN="${SEQ_LEN:-96}"
PRED_LENS="${PRED_LENS:-24}"
FEATURE_MODE="${FEATURE_MODE:-multivariate}"
OUTPUT_DIR="${OUTPUT_DIR:-results/time_series_etth1_ssml_confirm_v2}"

REGRESSION_IMITATION_LOSS="${REGRESSION_IMITATION_LOSS:-huber}"
LAMBDA_IMITATION="${LAMBDA_IMITATION:-0.005}"
MARGIN="${MARGIN:-0.05}"
WARMUP_EPOCHS="${WARMUP_EPOCHS:-30}"
IMITATION_DECAY_START_EPOCH="${IMITATION_DECAY_START_EPOCH:-30}"
IMITATION_DECAY_END_EPOCH="${IMITATION_DECAY_END_EPOCH:-40}"
IMITATION_DECAY_MIN_SCALE="${IMITATION_DECAY_MIN_SCALE:-0.0}"
SSML_TOPK_RATIO="${SSML_TOPK_RATIO:-0.01}"
HETERO_SSML_ONE_WAY="${HETERO_SSML_ONE_WAY:-1}"
SSML_SUPERVISED_HOTSPOT_ALPHA="${SSML_SUPERVISED_HOTSPOT_ALPHA:-0.5}"
SSML_GATE_SCORE_MODE="${SSML_GATE_SCORE_MODE:-peer_better_student_error}"
SSML_SCORE_TRANSFORM="${SSML_SCORE_TRANSFORM:-none}"
SSML_GUIDANCE_MODE="${SSML_GUIDANCE_MODE:-reweight_only}"

echo "[time_series_etth1_ssml_confirm] output_dir=$OUTPUT_DIR"
echo "[time_series_etth1_ssml_confirm] gpu=$GPU seeds=$SEEDS"
echo "[time_series_etth1_ssml_confirm] lambda=$LAMBDA_IMITATION margin=$MARGIN topk=$SSML_TOPK_RATIO warmup=$WARMUP_EPOCHS"
echo "[time_series_etth1_ssml_confirm] ssml_supervised_hotspot_alpha=$SSML_SUPERVISED_HOTSPOT_ALPHA"
echo "[time_series_etth1_ssml_confirm] ssml_gate_score_mode=$SSML_GATE_SCORE_MODE"
echo "[time_series_etth1_ssml_confirm] ssml_score_transform=$SSML_SCORE_TRANSFORM"
echo "[time_series_etth1_ssml_confirm] ssml_guidance_mode=$SSML_GUIDANCE_MODE"

CUDA_VISIBLE_DEVICES="$GPU" \
METHODS="independent dml ssml" \
DATASETS="etth1" \
SEEDS="$SEEDS" \
MODEL_PAIRS="$MODEL_PAIRS" \
REQUIRE_DISTINCT_PEER="1" \
EPOCHS="$EPOCHS" \
BATCH_SIZE="$BATCH_SIZE" \
NUM_WORKERS="$NUM_WORKERS" \
DEVICE="$DEVICE" \
OUTPUT_DIR="$OUTPUT_DIR" \
SEQ_LEN="$SEQ_LEN" \
PRED_LENS="$PRED_LENS" \
REGRESSION_IMITATION_LOSS="$REGRESSION_IMITATION_LOSS" \
LAMBDA_IMITATION="$LAMBDA_IMITATION" \
MARGIN="$MARGIN" \
WARMUP_EPOCHS="$WARMUP_EPOCHS" \
IMITATION_DECAY_START_EPOCH="$IMITATION_DECAY_START_EPOCH" \
IMITATION_DECAY_END_EPOCH="$IMITATION_DECAY_END_EPOCH" \
IMITATION_DECAY_MIN_SCALE="$IMITATION_DECAY_MIN_SCALE" \
SSML_TOPK_RATIO="$SSML_TOPK_RATIO" \
HETERO_SSML_ONE_WAY="$HETERO_SSML_ONE_WAY" \
SSML_SUPERVISED_HOTSPOT_ALPHA="$SSML_SUPERVISED_HOTSPOT_ALPHA" \
SSML_GATE_SCORE_MODE="$SSML_GATE_SCORE_MODE" \
SSML_SCORE_TRANSFORM="$SSML_SCORE_TRANSFORM" \
SSML_GUIDANCE_MODE="$SSML_GUIDANCE_MODE" \
FEATURE_MODE="$FEATURE_MODE" \
bash scripts/paper_rerun/run_core_time_series.sh
